ProCalendar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cal.urls')),
]

# Creates path for login view
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

cal/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'cal'
urlpatterns = [
    url(r'^$', login_required(views.CalendarView.as_view()), name='home'),
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', login_required(views.CalendarView.as_view()), name='calendar'),
    url(r'^tasks/$', login_required(views.TaskView.as_view()), name='tasks'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),

    path('register/', views.registerPage, name='registerPage'),

    path('settings/', views.settingsPage, name='settingsPage'),

    path('sync/', views.sync_menu, name='sync_menu'),

    path('sync/sync_to_google', views.sync_to_google,
         name='sync_to_google')

    #path('base/', views.dummy_action, name='dummy_action')

]

cal/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from cal.gcal_sync.format_datetime import format_datetime

# Create your models here.

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    CATEGORY_CHOICES = [("Important", "Important"), ("Tentative", "Tentative"), ("Recurrent", "Recurrent"), ("Normal", "Normal")]
    category = models.CharField(max_length=40, choices=CATEGORY_CHOICES, default="NORMAL")
    COLOR_CHOICES = [("dddddd","WHITE"),("ff4444","RED"), ("44ff44", "GREEN"), ("4444ff", "BLUE")]
    color = models.CharField(max_length=40, choices=COLOR_CHOICES, default="WHITE")
    the_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    gcal_id = models.TextField(max_length=1024, null=True, blank=True)

    @property
    def get_html_url(self):
        url = reverse('cal:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

    @property
    def to_gcal_body(self):
        return {
            "kind": "calendar#event",
            "start": {"dateTime": format_datetime(
                self.start_time)},
            "end": {
                "dateTime": format_datetime(self.end_time)},
            "summary": self.title,
            "description": self.description
        }


class Token(models.Model):
    token = models.TextField()
    refresh_token = models.TextField()
    token_uri = models.TextField()
    client_id = models.TextField()
    client_secret = models.TextField()
    scopes = models.TextField()
    expiry = models.TextField()
    the_user = models.ForeignKey(User, on_delete=models.CASCADE,
                                 null=False, blank=False)

    @property
    def to_dict(self):
        return {
            "token": self.token,
            "refresh_token": self.refresh_token,
            "token_uri": self.token_uri,
            "client_id": self.client_id,
            "client_secret": self.client_secret,
            "scopes": self.scopes,
            "expiry": self.expiry,
            "the_user": self.the_user
        }

cal/forms.py
from django.forms import ModelForm, DateInput
from cal.models import Event
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = ['title', 'description', 'start_time', 'end_time', 'category', 'color']

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats to parse HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)


class CreateUserForm(UserCreationForm):
  class Meta:
    model = User
    fields = ['username', 'email', 'password1', 'password2']

cal/views.py
from __future__ import print_function

from datetime import datetime, timedelta, date

from django.db.models import Model
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required


from .models import *
from .utils import Calendar, Tasks
from .forms import EventForm, CreateUserForm

from cal.gcal_sync.format_datetime import format_datetime
from googleapiclient.discovery import build
import os.path
from os.path import dirname, join
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from cal.models import Token
import json
from googleapiclient.errors import HttpError


def index(request):
    return HttpResponse('hello')


class CalendarView(generic.ListView):
    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month, self.request.user.id)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month



class TaskView(generic.ListView):
    model = Event
    template_name = 'cal/taskview.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date_tasks(self.request.GET.get('date', None))
        tasks = Tasks(d.year, d.month, d.day, self.request.user.id)
        html_tasks = tasks.formatweek()
        context['task_list'] = mark_safe(html_tasks)
        context['prev_week'] = prev_week(d)
        context['next_week'] = next_week(d)
        return context

def get_date_tasks(req_day):
    if req_day:
        year, month, day = (int(x) for x in req_day.split('-'))
        return date(year, month, day)
    return datetime.today()


def prev_week(d):
    current = d
    prev_week = current - timedelta(days=7)
    date = 'date=' + str(prev_week.year) + '-' + str(prev_week.month) + '-' + str(prev_week.day)
    return date


def next_week(d):
    current = d
    next_week = current + timedelta(days=7)
    date = 'date=' + str(next_week.year) + '-' + str(next_week.month) + '-' + str(next_week.day)
    return date



@login_required(login_url='login')
def event(request, event_id=None):
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()
    instance.the_user = get_object_or_404(User, pk=request.user.id)
    form = EventForm(request.POST or None, instance=instance)

    if request.POST and form.is_valid():
        # if '_edit' in request.POST:
        if '_delete' in request.POST:
            instance.delete()
        else:
            form.save()

        return HttpResponseRedirect(reverse('cal:calendar'))

    return render(request, 'cal/event.html', {'form': form})


def registerPage(request):
    form = CreateUserForm

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,'Account was created for ' + username)
            return redirect('login')

    context = {'form':form}
    return render(request, 'registration/register.html', context)


def settingsPage(request):
    return render(request, 'cal/settings.html')


"""Stuff needed for syncing"""
# Returns a list of events that start on or after start_date and end
# on or before end_date
def filter_events_by_date(start_date, end_date, user_id):
    start_datetime = datetime(start_date.year, start_date.month,
                              start_date.day)
    maxtime = datetime.max
    end_datetime = datetime(end_date.year, end_date.month,
                            end_date.day, maxtime.hour,
                            maxtime.minute, maxtime.second,
                            maxtime.microsecond)
    event_list = Event.objects.filter(start_time__range=(
        start_datetime, end_datetime)).filter(end_time__range=(
        start_datetime, end_datetime)).filter(the_user_id=user_id)

    return event_list

# Adds an event from ProCal to google calendar and records the google
# calendar event's gcal_id
def add_new_event_to_google(service, event):
    _event = service.events().insert(calendarId='primary',
                                     body=event.to_gcal_body).execute()
    event.gcal_id = service.events().get(calendarId='primary',
                                         eventId=_event[
                                             'id']).execute()['id']
    event.save()
    return event

# Updates an event on Google Calendar using information from the
# event that has the same gcal_id on ProCal. Returns True if
# succesful and False if it isn't
def update_google_event(service, event):
    if not event.gcal_id:
        return False

    try:
        service.events().update(calendarId='primary',
                                        eventId=event.gcal_id,
                                        body=event.to_gcal_body).execute()
    except:
        print("Something went wrong")
        return False

    return True


# Adds events that fall within a date-range specified by the user from
# the app to google calendar and updates existing ones.
def sync_to_google(request):
    print("yeah this is happening")
    creds = get_credentials(request.user.id)
    service = build('calendar', 'v3', credentials=creds)
    event_list = filter_events_by_date(date.fromisoformat(
        request.POST['start_date']),
        date.fromisoformat(request.POST['end_date']), request.user.id)

    print(len(event_list))

    for i in event_list:
        # If this event has already been synced to Google Calendar,
        # the event gets updated. If it hasn't been synced already,
        # it gets synced and its gcal_id gets recorded
        foo = update_google_event(service=service, event=i)
        if not foo:
            add_new_event_to_google(service=service, event=i)

    return redirect('cal:sync_menu')


def sync_menu(request):
    print(f'USER ID:{request.user.id}')
    print(f'USER NAME:{request.user.username}')
    return render(request, 'sync/sync_menu.html')

def get_credentials(user_id):
    SCOPES = ['https://www.googleapis.com/auth/calendar']
    creds = None
    existing_creds = None
    try:
        existing_creds = Token.objects.get(the_user_id=user_id)
    except:
        existing_creds = None

    if existing_creds:
        # Load creds if there are any for this user (add later)
        foo = existing_creds.to_dict
        del foo["the_user"]
        creds = Credentials.from_authorized_user_info(
            foo, SCOPES)

    # Let the user log in if there aren't any valid credentials
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                join(dirname(__file__), "credentials.json"), SCOPES)
            creds = flow.run_local_server(port=0)
            print(type(json.loads(creds.to_json())))

        # Save credentials for next run
        cred_dict = json.loads(creds.to_json())
        # Create new entry in Token table if there isn't one for this
        # user, or just make a new one for this user if there isn't one
        # already. (part of saving creds for next run)
        if not existing_creds:
            new_entry = Token(token=cred_dict['token'],
                              refresh_token=cred_dict['refresh_token'],
                              token_uri=cred_dict['token_uri'],
                              client_id=cred_dict['client_id'],
                              client_secret=cred_dict['client_secret'],
                              scopes=cred_dict['scopes'],
                              expiry=cred_dict['expiry'],
                              the_user_id=user_id)
            new_entry.save()
        else:
            updated_entry = Token.objects.get(the_user_id=user_id)
            updated_entry.token = cred_dict['token']
            updated_entry.refresh_token = cred_dict['refresh_token']
            updated_entry.token_uri = cred_dict['token_uri']
            updated_entry.client_id = cred_dict['client_id']
            updated_entry.client_secret = cred_dict['client_secret']
            updated_entry.scopes = cred_dict['scopes']
            updated_entry.expiry = cred_dict['expiry']
            updated_entry.save()

    return creds

cal/templates/cal/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
    <title>Calendar</title>
</head>
<body>
    <h1 class="title">{% block title %}{% endblock %}</h1>
    <hr>
    {% block content %}

    {% endblock %}
    <!-- Optional JavaScript -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    {% block script %}
        <script src="{% static 'cal/js/ThemeSwap.js' %}"></script>
    {% endblock %}
</body>
</html>

cal/templates/cal/calendar.html
{% extends 'cal/base.html' %}

{% block title %}
    Calendar
{% endblock %}


{% block content %}
    <div class="accountInfo">
        Logged in as {{ user.get_username }}
        <a class="btn btn-info" href="{% url 'cal:settingsPage' %}"> Settings </a>
    </div>
    <div class="clearfix">
        <a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Previous Month </a>
        <a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month </a>
        <a class="btn btn-info right" href="{% url 'cal:event_new' %}"> New Event </a>
    </div>

{{ calendar }}
{% endblock %}

cal/templates/cal/event.html
{% extends 'cal/base.html' %}

{% block title %}
    Event
{% endblock %}

{% block content %}
    <div class="clearfix">
        <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
        <a class="btn btn-info left" href="{% url 'cal:tasks' %}">Task View</a>
    </div>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ field.label }} <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <table class="form form-table">
            {{ form }}
            <tr>
                <td colspan="2">
                    <button type="submit" value="Edit" name="_edit" class="btn btn-info right"> Submit </button>
                    <button type="submit" value="Delete" name="_delete" class="btn btn-info right"> Delete </button>
                </td>
            </tr>
        </table>
    </form>

{% endblock %}

cal/templates/cal/settings.html
{% extends 'cal/base.html' %}

{% block title %}
    Settings
{% endblock %}

{% block content %}
    <div class="divContainer">

        <div class="clearfix">
            <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
            <a class="btn btn-info left" href="{% url 'cal:tasks' %}">Task View</a>
        </div>

        <h1 class="settingsHeader">
            Switch Theme
        </h1>
        <hr>
        <div class="settings">
            <button class="btn btn-info" id="btn-toggle">
                Toggle Theme
            </button>
        </div>

        <h1 class="settingsHeader">
            Sync Google Calender
        </h1>
        <hr>
        <div class="settings">
            <a class="btn btn-info" href="{% url 'cal:sync_menu' %}"> Sync Events </a>
        </div>

        <h1 class="settingsHeader">
            Logout
        </h1>
        <hr>
        <div class="settings">
            <a class="btn btn-info" href="{% url 'logout' %}"> Logout </a>
        </div>

    </div>
{% endblock %}

cal/templates/cal/taskview.html
{% extends 'cal/base.html' %}

{% block title %}
    Task View
{% endblock %}

{% block content %}
    <div class="accountInfo">
        <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
        Logged in as {{ user.get_username }}
        <a class="btn btn-info" href="{% url 'cal:settingsPage' %}"> Settings </a>
    </div>
    <div class="clearfix">

        <a class="btn btn-info left" href="{% url 'cal:tasks' %}?{{ prev_week }}"> Previous Week </a>
        <a class="btn btn-info left" href="{% url 'cal:tasks' %}?{{ next_week }}"> Next Week </a>
        <a class="btn btn-info right" href="{% url 'cal:event_new' %}"> New Event </a>
    </div>

{{ task_list }}
{% endblock %}